In [3]:
import numpy as np

In [156]:
#Banking Industry data with 10 rows * 5 columns
#Columns : Customer_ID, Account_Balance, Credit_Score, Transaction_Count, Years_Active
banking_data = np.array([
    [101, 10000, 720, 45, 5],
    [102,  8500, 680, 30, 3],
    [103, 12000, 750, 60, 7],
    [104,  5000, 640, 20, 2],
    [105,  9500, 700, 40, 4],
    [106, 15000, 780, 75, 8],
    [107,  3000, 610, 15, 1],
    [108, 11000, 730, 55, 6],
    [109,  4000, 650, 25, 2],
    [110,  9000, 690, 35, 3]
])
print(banking_data)

[[  101 10000   720    45     5]
 [  102  8500   680    30     3]
 [  103 12000   750    60     7]
 [  104  5000   640    20     2]
 [  105  9500   700    40     4]
 [  106 15000   780    75     8]
 [  107  3000   610    15     1]
 [  108 11000   730    55     6]
 [  109  4000   650    25     2]
 [  110  9000   690    35     3]]


In [ ]:
print(f"Data shape: {banking_data.shape}")
print(f"Data type: {banking_data.dtype}")

Data shape: (10, 5)
Data type: int64


Question 1: Array Creation and Manipulation


In [10]:
#Q1.1: Create a 4x4 identity matrix using np.eye()
identity_matrix = np.eye(4)
print(identity_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [13]:
#Q1.2: Create an array of 8 zeros using np.zeros()
zero_array  = np.zeros(8)
print(zero_array)

[0. 0. 0. 0. 0. 0. 0. 0.]


In [14]:
#Q1.3: Create an array of 6 ones using np.ones()
ones_array = np.ones(6)
print(ones_array)

[1. 1. 1. 1. 1. 1.]


In [17]:
#Q1.4: Create an array with values from 0 to 15 using np.arange()
array1 = np.arange(0,15)
print(array1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [18]:
#Q1.5: Create an array with 8 evenly spaced values from 0 to 100 using np.linspace()
array2 = np.linspace(0,100,8)
print(array2)

[  0.          14.28571429  28.57142857  42.85714286  57.14285714
  71.42857143  85.71428571 100.        ]


Question 2: Array Attributes and Information



In [19]:
#Q2.1: What is the shape of the banking_data array?
print(banking_data.shape)

(10, 5)


In [20]:
#Q2.1: What is the shape of the banking_data array?
print(banking_data.dtype)

int64


In [22]:
#Q2.3: What is the size (total number of elements) of the banking_data array?
print(banking_data.size)

50


In [24]:
#Q2.4: What is the number of dimensions of the banking_data array?
print(banking_data.ndim)

2


In [25]:
#Q2.5: What is the memory size of the banking_data array in bytes?
print(banking_data.nbytes)

400


Question 3: Indexing and Slicing


In [27]:
#Q3.1: Extract the first row of banking_data
print(banking_data[0])

[  101 10000   720    45     5]


In [30]:
#Q3.2: Extract the last row of banking_data
print(banking_data[-1])  #print(banking_data[9])

[ 110 9000  690   35    3]


In [37]:
#Q3.3: Extract the Account_Balance column (column index 1)
print(banking_data[:,1])

[10000  8500 12000  5000  9500 15000  3000 11000  4000  9000]


In [41]:
#Q3.4: Extract the first 4 rows and first 3 columns
print(banking_data[:4,:3])

[[  101 10000   720]
 [  102  8500   680]
 [  103 12000   750]
 [  104  5000   640]]


In [46]:
#Q3.5: Extract rows 3 to 7 (inclusive)
print(banking_data[3:8,])

[[  104  5000   640    20     2]
 [  105  9500   700    40     4]
 [  106 15000   780    75     8]
 [  107  3000   610    15     1]
 [  108 11000   730    55     6]]


Question 4: Mathematical Operations


In [48]:
#Q4.1: Calculate the sum of all account balances
print("Sum of account balances :",np.sum(banking_data[:,1]))

Sum of account balances : 87000


In [49]:
#Q4.2: Calculate the mean account balance
print("Mean of account balance :", np.mean(banking_data[:,1]))

Mean of account balance : 8700.0


In [50]:
#Q4.3: Calculate the standard deviation of account balances
print("Standard deviation of account balances :", np.std(banking_data[:,1]))

Standard deviation of account balances : 3558.089374931439


In [52]:
#Q4.4: Calculate the variance of account balances
print("Variance of account balances :", np.var(banking_data[:,1]))

Variance of account balances : 12660000.0


In [53]:
#Q4.5: Calculate the median account balance
print("Median of account balances :", np.median(banking_data[:,1]))

Median of account balances : 9250.0


Question 5: Statistical Functions


In [60]:
#Q5.1: Find the minimum and maximum account balances
print("Minimum Account balance :$",np.min(banking_data[:,1]))
print("\nMaximum Account balance :$",np.max(banking_data[:,1]))


Minimum Account balance :$ 3000

Maximum Account balance :$ 15000


In [57]:
#Q5.2: Find the minimum and maximum credit scores
print("Minimum credit score :",np.min(banking_data[:,2]))
print("\nMaximum credit score:",np.max(banking_data[:,2]))

Minimum credit score : 610

Maximum credit score: 780


In [58]:
#Q5.3: Calculate the percentile values for account balances (25th, 50th, 75th)

percentiles = np.percentile(banking_data[:, 1], [25, 50, 75])
print(f"25th percentile: ${percentiles[0]:.2f}")
print(f"50th percentile: ${percentiles[1]:.2f}")
print(f"75th percentile: ${percentiles[2]:.2f}")


25th percentile: $5875.00
50th percentile: $9250.00
75th percentile: $10750.00


In [62]:
#Q5.4: Calculate the correlation between account balance and credit score
print("Correlation between account balance and credit score :", np.corrcoef(banking_data[:,1],banking_data[:,2])[0,1])

Correlation between account balance and credit score : 0.9821417309135924


In [ ]:
#Q5.5: Calculate the covariance between account balance and credit score
print("Covariance between account balance and credit score :", np.cov(banking_data[:,1],banking_data[:,2])[0,1])

Covariance between account balance and credit score : 192777.77777777778


Question 6: Array Reshaping and Manipulation



In [67]:
#Q6.1: Reshape the banking_data to 5 rows × 10 columns
print("Reshapped Banking Data :\n", banking_data.reshape(5,10))

Reshapped Banking Data :
 [[  101 10000   720    45     5   102  8500   680    30     3]
 [  103 12000   750    60     7   104  5000   640    20     2]
 [  105  9500   700    40     4   106 15000   780    75     8]
 [  107  3000   610    15     1   108 11000   730    55     6]
 [  109  4000   650    25     2   110  9000   690    35     3]]


In [70]:
#Q6.2: Flatten the banking_data to a 1D array
print("Flattened Banking Data :", banking_data.flatten)

Flattened Banking Data : <built-in method flatten of numpy.ndarray object at 0x000002CF410529D0>


In [72]:
#Q6.3: Transpose the banking_data
print("Transpose of Banking Data :\n",banking_data.T)

Transpose of Banking Data :
 [[  101   102   103   104   105   106   107   108   109   110]
 [10000  8500 12000  5000  9500 15000  3000 11000  4000  9000]
 [  720   680   750   640   700   780   610   730   650   690]
 [   45    30    60    20    40    75    15    55    25    35]
 [    5     3     7     2     4     8     1     6     2     3]]


In [ ]:
#Q6.4: Split the banking_data into 2 equal parts vertically
#splits data by row
print("Banking data split vertically :\n")
split_vertically = np.vsplit(banking_data,2)
print("First part :\n",split_vertically[0])
print("Second part :\n",split_vertically[1] )


Banking data split vertically :

First part :
 [[  101 10000   720    45     5]
 [  102  8500   680    30     3]
 [  103 12000   750    60     7]
 [  104  5000   640    20     2]
 [  105  9500   700    40     4]]
Second part :
 [[  106 15000   780    75     8]
 [  107  3000   610    15     1]
 [  108 11000   730    55     6]
 [  109  4000   650    25     2]
 [  110  9000   690    35     3]]


In [ ]:
#Q6.5: Split the banking_data into 2 equal parts horizontally
#splits data by columns

print("Banking data split horizontally :\n")
split_horizontally = np.hsplit(banking_data , 2 )
print("First part :\n",split_horizontally[0])
print("Second part :\n",split_horizontally[1] )


Banking data split horizontally :



ValueError: array split does not result in an equal division

In [ ]:
banking_data

array([[  101, 10000,   720,    45,     5],
       [  102,  8500,   680,    30,     3],
       [  103, 12000,   750,    60,     7],
       [  104,  5000,   640,    20,     2],
       [  105,  9500,   700,    40,     4],
       [  106, 15000,   780,    75,     8],
       [  107,  3000,   610,    15,     1],
       [  108, 11000,   730,    55,     6],
       [  109,  4000,   650,    25,     2],
       [  110,  9000,   690,    35,     3]])

Question 7: Logical Operations and Filtering



In [ ]:
#Q7.1: Find customers with account balance greater than $100,000
account_balance = banking_data[banking_data[:,1] >100000]
print("customers with account balance greater than $100,000 :",account_balance)

[]


In [92]:
#Q7.2: Find customers with credit score greater than 800
credit_score = banking_data[banking_data[:,2] > 800]
print("customers with credit score greater than 800 :",credit_score)

customers with credit score greater than 800 : []


In [94]:
#Q7.3: Find customers with transaction count greater than 50 AND credit score less than 750
transaction = banking_data[(banking_data[:,3] > 50) & (banking_data[:,2] < 750)]
print("customers with transaction count greater than 50 AND credit score less than 750 :",transaction)

customers with transaction count greater than 50 AND credit score less than 750 : [[  108 11000   730    55     6]]


In [99]:
#Q7.4: Count how many customers have account balance between $10,000 and $100,000
question = np.sum((banking_data[:,1] >= 10000) & (banking_data[:,1] <= 100000))
print("customers have account balance between $10,000 and $100,000 :",question)


customers have account balance between $10,000 and $100,000 : 4


In [101]:
#Q7.5: Find the index of the customer with the highest credit score
highest_credit_score = np.argmax(banking_data[:,2])+1
print("Index of the customer with the highest credit score :",highest_credit_score)

Index of the customer with the highest credit score : 6


Question 8: Sorting and Searching


In [105]:
#Q8.1: Sort the banking_data by account balance (ascending)
print("Ascending order :\n",banking_data[banking_data[:,1].argsort()])

Ascending order :
 [[  107  3000   610    15     1]
 [  109  4000   650    25     2]
 [  104  5000   640    20     2]
 [  102  8500   680    30     3]
 [  110  9000   690    35     3]
 [  105  9500   700    40     4]
 [  101 10000   720    45     5]
 [  108 11000   730    55     6]
 [  103 12000   750    60     7]
 [  106 15000   780    75     8]]


In [107]:
#Q8.2: Sort the banking_data by credit score (descending)
print("Decending order :\n",banking_data[(-banking_data[:,1]).argsort()])


Decending order :
 [[  106 15000   780    75     8]
 [  103 12000   750    60     7]
 [  108 11000   730    55     6]
 [  101 10000   720    45     5]
 [  105  9500   700    40     4]
 [  110  9000   690    35     3]
 [  102  8500   680    30     3]
 [  104  5000   640    20     2]
 [  109  4000   650    25     2]
 [  107  3000   610    15     1]]


In [114]:
#Q8.3: Find the indices that would sort the array by years active
array = banking_data[banking_data[:,4].argsort()]
print("sort the array by years active:\n",array)
print("indices that would sort the array by years active :",np.argsort(banking_data[:,4])+1)

sort the array by years active:
 [[  107  3000   610    15     1]
 [  104  5000   640    20     2]
 [  109  4000   650    25     2]
 [  102  8500   680    30     3]
 [  110  9000   690    35     3]
 [  105  9500   700    40     4]
 [  101 10000   720    45     5]
 [  108 11000   730    55     6]
 [  103 12000   750    60     7]
 [  106 15000   780    75     8]]
indices that would sort the array by years active : [ 7  4  9  2 10  5  1  8  3  6]


In [125]:
#Q8.4: Find the customer with the second highest account balance
second_highest = banking_data[banking_data[:,1].argsort()][-2]
print("customer with the second highest account balance :",second_highest)

customer with the second highest account balance : [  103 12000   750    60     7]


In [128]:
#Q8.5: Find the customer with the lowest transaction count
lowest_transaction_count = np.argmin(banking_data[:,4])+1
print("customer with the lowest transaction count :",lowest_transaction_count)

customer with the lowest transaction count : 7


Question 9: Mathematical Functions


In [131]:
#Q9.1: Calculate the absolute values of all elements
print("Absolute Values of Banking Data :\n",np.abs(banking_data))

Absolute Values of Banking Data :
 [[  101 10000   720    45     5]
 [  102  8500   680    30     3]
 [  103 12000   750    60     7]
 [  104  5000   640    20     2]
 [  105  9500   700    40     4]
 [  106 15000   780    75     8]
 [  107  3000   610    15     1]
 [  108 11000   730    55     6]
 [  109  4000   650    25     2]
 [  110  9000   690    35     3]]


In [133]:
#Q9.2: Calculate the square root of all account balances
square_roots = np.sqrt(banking_data[:,1])
print(" square root of all account balances :\n", square_roots)

 square root of all account balances :
 [100.          92.19544457 109.5445115   70.71067812  97.46794345
 122.47448714  54.77225575 104.88088482  63.2455532   94.86832981]


In [134]:
#Q9.3: Calculate the square of all credit scores
print(" square of all credit scores :\n",np.square(banking_data[:,2]))

 square of all credit scores :
 [518400 462400 562500 409600 490000 608400 372100 532900 422500 476100]


In [135]:
#Q9.4: Calculate the exponential of all transaction counts
print("Exponential of all transaction counts :\n",np.exp(banking_data[:,3]))

Exponential of all transaction counts :
 [3.49342711e+19 1.06864746e+13 1.14200739e+26 4.85165195e+08
 2.35385267e+17 3.73324200e+32 3.26901737e+06 7.69478527e+23
 7.20048993e+10 1.58601345e+15]


In [137]:
#Q9.5: Calculate the natural logarithm of all account balances
print("Natural logarithm of all account balances :\n",np.log(banking_data[:,1]))

Natural logarithm of all account balances :
 [9.21034037 9.04782144 9.39266193 8.51719319 9.15904708 9.61580548
 8.00636757 9.30565055 8.29404964 9.10497986]


Question 10: Advanced Operations


In [140]:
#Q10.1: Calculate the cumulative sum of account balances
print("Cumulative sum of account balances :\n", np.cumsum(banking_data[:,1]))

Cumulative sum of account balances :
 [10000 18500 30500 35500 45000 60000 63000 74000 78000 87000]


In [141]:
#Q10.2: Calculate the cumulative product of transaction counts
print("Cumulative product of transaction counts :\n",np.cumprod(banking_data[:,3]))

Cumulative product of transaction counts :
 [              45             1350            81000          1620000
         64800000       4860000000      72900000000    4009500000000
  100237500000000 3508312500000000]


In [ ]:
#Q10.3: Calculate the difference between consecutive account balances
print("Difference between consecutive account balances :\n", np.diff(banking_data[:,1]))


Difference between consecutive account balances :
 [ -1500   3500  -7000   4500   5500 -12000   8000  -7000   5000]


<small>
Finding Gradient

First element (i = 0):  
grad[0] = f[1] − f[0]  

Last element (i = n−1):  
grad[n−1] = f[n−1] − f[n−2]  

Middle elements (0 < i < n−1):  
grad[i] = (f[i+1] − f[i−1]) / 2  
</small>


In [143]:
#Q10.4: Calculate the gradient of account balances
print("Gradient of account balances :\n",np.gradient(banking_data[:,1]))

Gradient of account balances :
 [-1500.  1000. -1750. -1250.  5000. -3250. -2000.   500. -1000.  5000.]



**Inputs**
- data: x1, x2, ..., xn
- number of bins: k = 5 ---> bins

**1) Find min and max**
- min = min(x)
- max = max(x)

**2) Compute bin width**
- bin_width = (max − min) / k

**3) Compute bin edges (k+1 numbers)**
- e0 = min
- e1 = min + bin_width
- e2 = min + 2*bin_width
- ...
- ek = max

**4) Count items in each bin**
- For j = 0 … k−2: Bin j is [ej, e(j+1)) → count values x with ej ≤ x < e(j+1)
- Last bin (j = k−1): [e(k−1), ek] → include right edge

**5) Output**
- counts = [count0, count1, …, count(k−1)]
- edges  = [e0, e1, …, ek]



In [145]:
#Q10.5: Calculate the histogram of account balances with 5 bins
print("histogram of account balances with 5 bins :\n",np.histogram(banking_data[:,1],bins=5))

histogram of account balances with 5 bins :
 (array([3, 0, 4, 2, 1]), array([ 3000.,  5400.,  7800., 10200., 12600., 15000.]))


Question 11: Random Numbers and Simulation


In [ ]:
#Q11.1: Generate 6 random integers between 1 and 1000
print(np.random.randint(1,1001,6))

array([ 38, 214,  68, 841,  43, 447], dtype=int32)

In [ ]:
#Q11.2: Generate 6 random floats between 0 and 1
print(np.random.random(6)) #basically generates random numbers between 0.0 to 1.0

[0.02633873 0.76568242 0.83742623 0.47760721 0.35533551 0.33556784]


In [ ]:
#Q11.3: Generate 6 random numbers from normal distribution (mean=700, std=100)
print(np.random.normal(700,100,6))   #np.random.normal(mean,std,n)

[477.25684325 655.90124903 780.25735185 617.72159245 735.28788445
 768.56858562]


In [158]:
#Q11.4: Shuffle the banking_data rows randomly
shuffle_copy = banking_data.copy()
np.random.shuffle(shuffle_copy)   # there's no undo if we shuffle the original data
print(shuffle_copy)    # so always create a copy


[[  102  8500   680    30     3]
 [  103 12000   750    60     7]
 [  106 15000   780    75     8]
 [  105  9500   700    40     4]
 [  110  9000   690    35     3]
 [  109  4000   650    25     2]
 [  108 11000   730    55     6]
 [  107  3000   610    15     1]
 [  101 10000   720    45     5]
 [  104  5000   640    20     2]]


In [157]:
banking_data

array([[  101, 10000,   720,    45,     5],
       [  102,  8500,   680,    30,     3],
       [  103, 12000,   750,    60,     7],
       [  104,  5000,   640,    20,     2],
       [  105,  9500,   700,    40,     4],
       [  106, 15000,   780,    75,     8],
       [  107,  3000,   610,    15,     1],
       [  108, 11000,   730,    55,     6],
       [  109,  4000,   650,    25,     2],
       [  110,  9000,   690,    35,     3]])

In [ ]:
#Q11.5: Set random seed to 123 and generate 4 random numbers
np.random.seed(123)                            #np.random.RandomState(123).random(4)
seeded_numbers =np.random.random(4)
print(seeded_numbers)

[0.69646919 0.28613933 0.22685145 0.55131477]


Question 12: Linear Algebra Operations


In [ ]:
#Q12.1: Calculate the dot product of account balance and credit score columns
dot_product = np.dot(banking_data[:,1],banking_data[:,2])   #ab= a1b1+ a2b2 +....+anbn
print(f"Dot product of account balance and credit score columns :{dot_product}")

Dot product of account balance and credit score columns :62200000


In [ ]:
#Q12.2: Calculate the cross product of first two rows
cross_product = np.cross(banking_data[0,:3],banking_data[1,:3])  #can be done on 2D or 3D
print(cross_product)  #a×b=(ay​bz​−az​by​,az​bx​−ax​bz​,ax​by​−ay​bx​)  matrix 

[ 680000    4760 -161500]


In [ ]:
#Q12.3: Calculate the norm (magnitude) of the account balance column
print("Norm (magnitude) of the account balance column :",np.linalg.norm(banking_data[:,1]))

norm (magnitude) of the account balance column : 29723.7278954037


In [ ]:
#Q12.4: Create a 3x3 matrix and calculate its determinant
matrix = np.random.randint(1,10,(3,3))   #np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)
determinant = np.linalg.det(matrix)
print("Determinant of 3x3 matrix :",round(determinant))

[[2 3 2]
 [2 4 6]
 [1 9 2]]
Determinant of 3x3 matrix : -58


In [178]:
#Q12.5: Calculate the inverse of the 3x3 matrix
matrix = np.random.randint(1,10,(3,3))
print(matrix)
inverse = np.linalg.inv(matrix)
print("Inverse of 3x3 matrix :\n",inverse)


[[4 5 4]
 [2 1 6]
 [9 7 9]]
Inverse of 3x3 matrix :
 [[-0.48529412 -0.25        0.38235294]
 [ 0.52941176  0.         -0.23529412]
 [ 0.07352941  0.25       -0.08823529]]


Question 13: String Operations


In [180]:
#Q13.1: Convert all customer IDs to strings
print("Converting all customer IDs to strings :\n",banking_data[:,0].astype(str))

Converting all customer IDs to strings :
 ['101' '102' '103' '104' '105' '106' '107' '108' '109' '110']


In [ ]:
#Q13.2: Check if any customer ID contains '100'
string1 = banking_data[:,0].astype(str)
contain_string_100 =np.char.find(string1,'100') >= 0  # condition(>=0)converts to boolen
print(contain_string_100)
print(np.any(contain_string_100))  #checks if at least one is True

[False False False False False False False False False False]
False


In [187]:
#Q13.3: Convert all customer IDs to uppercase (if they were strings)
string1 =banking_data[:,0].astype(str)
upper_case= np.char.upper(string1)
print("Converting all customer IDs to uppercase :",upper_case)

Converting all customer IDs to uppercase : ['101' '102' '103' '104' '105' '106' '107' '108' '109' '110']


In [188]:
#Q13.4: Count the length of each customer ID string
print("length of each customer ID string :\n",np.char.str_len(string1))

length of each customer ID string :
 [3 3 3 3 3 3 3 3 3 3]


In [192]:
#Q13.5: Replace '100' with 'CUST' in customer IDs
replace_100 = np.char.replace(string1,'101','CUST')
#replace_100 = np.char.replace(string1,'100','CUST')
print(replace_100)

['CUST' '102' '103' '104' '105' '106' '107' '108' '109' '110']


Question 14: Date and Time Operations


In [193]:
#Q14.1: Convert years active to months
print("Years active to months :", banking_data[:,4]*12)

Years active to months : [60 36 84 24 48 96 12 72 24 36]


In [194]:
#Q14.2: Calculate the average years active
print("Average years active :",np.mean(banking_data[:,4]))

Average years active : 4.1


In [199]:
#Q14.3: Find customers who have been active for more than 5 years
print("No. of Customers who have been active for more than 5 years :",np.sum(banking_data[:,4] >5))
print("Customers who have been active for more than 5 years :\n",banking_data[banking_data[:,4] >5])


No. of Customers who have been active for more than 5 years : 3
Customers who have been active for more than 5 years :
 [[  103 12000   750    60     7]
 [  106 15000   780    75     8]
 [  108 11000   730    55     6]]


In [201]:
#Q14.4: Calculate the total time all customers have been active (in years)
print("Total time all customers have been active (in years) :",np.sum(banking_data[:,4]))

Total time all customers have been active (in years) : 41


In [203]:
#Q14.5: Find the customer with the shortest time active
cust1 = np.argmin(banking_data[:,4])
time = banking_data[cust1]
print("customer with the shortest time active :",time)

customer with the shortest time active : [ 107 3000  610   15    1]


Question 15: Advanced Array Operations


In [208]:
#Q15.1: Apply a function to calculate 5% interest on all account balances
interest = banking_data[:,1] *0.05
amt = banking_data[:,1] + interest
print("5 percent interest on all account balances :\n",amt)

5 percent interest on all account balances :
 [10500.  8925. 12600.  5250.  9975. 15750.  3150. 11550.  4200.  9450.]


In [ ]:
def interest(x):
   return x + x *0.05
   
x =banking_data[:,1]
print(interest(x))

# def apply_interest(balance):
#     return balance * 1.05  # Adds 5% interest

# # Applying function to the account balance column
# updated_balances = np.vectorize(apply_interest)(banking_data[:, 1]) //np.vectorize --lets you apply this function element-wise to the entire NumPy array.

# print("\nQ15.1: Updated balances after applying 5% interest:\n", updated_balances)

[10500.  8925. 12600.  5250.  9975. 15750.  3150. 11550.  4200.  9450.]


In [222]:
#Q15.2: Use np.where to categorize customers by balance ranges
amt = banking_data[:,1]
categories = np.where(amt < 5000, "Low",
    np.where(amt <= 10000, "Medium", "High"))
print(categories)

['Medium' 'Medium' 'High' 'Medium' 'Medium' 'High' 'Low' 'High' 'Low'
 'Medium']


In [ ]:
#Q15.4: Use np.piecewise to apply different interest rates based on balance
def low_balance(x): return x * 1.02
def mid_balance(x): return x * 1.05
def high_balance(x): return x * 1.07

balances = np.piecewise(
    banking_data[:,1],
    [banking_data[:,1] < 5000,
    (banking_data[:,1] < 10000) & (banking_data[:,1] >= 5000),
     banking_data[:,1] >= 10000],
    [low_balance,mid_balance,high_balance]   #np.piecewise(x, condlist, funclist, *args, **kwargs)
    
)
print(balances)

[10700  8925 12840  5250  9975 16050  3060 11770  4080  9450]


In [ ]:
#Q15.5: Use np.apply_along_axis to calculate the sum of each row
row_sums = np.apply_along_axis(np.sum, 1, banking_data)  #np.apply_along_axis(func, axis, array)
print(row_sums)

[10871  9315 12920  5766 10349 15969  3733 11899  4786  9838]


Question 16: Array Concatenation and Stacking


In [253]:
#Q16.1: Concatenate two arrays horizontally using np.hstack()
array1 = np.random.randint(0,10,5)
array2 = np.random.randint(0,10,5)
print(array1,array2)
horizontal_stack = np.hstack([array1,array2])
print(horizontal_stack)


[9 2 4 3 0] [3 7 7 2 5]
[9 2 4 3 0 3 7 7 2 5]


In [255]:
#Q16.2: Concatenate two arrays vertically using np.vstack()
array1 = np.random.randint(0,10,5)
array2 = np.random.randint(0,10,5)
print(array1,array2)
vertical_stack = np.vstack([array1,array2])
print(vertical_stack)


[3 3 3 1 7] [6 3 1 7 2]
[[3 3 3 1 7]
 [6 3 1 7 2]]


In [261]:
#Q16.3: Concatenate arrays along a specific axis using np.concatenate()
array1 = np.random.randint(0,10,5)
array2 = np.random.randint(0,10,5)
print(array1,array2)
concatenate_array = np.concatenate([array1,array2],axis=0)
print(concatenate_array)


[1 8 4 1 6] [5 9 0 3 1]
[1 8 4 1 6 5 9 0 3 1]


In [265]:
#Q16.4: Stack arrays depth-wise using np.dstack()
array1 = np.random.randint(0,10,5)
array2 = np.random.randint(0,10,5)
print(array1,array2)
dstacked = np.dstack([array1,array2])
print(dstacked)

[1 0 0 2 6] [5 9 1 5 3]
[[[1 5]
  [0 9]
  [0 1]
  [2 5]
  [6 3]]]


In [266]:
#Q16.5: Create a column stack using np.column_stack()
array1 = np.random.randint(0,10,5)
array2 = np.random.randint(0,10,5)
print(array1,array2)
col_stacked = np.column_stack([array1,array2])
print(col_stacked)


[6 4 7 1 6] [0 3 1 3 0]
[[6 0]
 [4 3]
 [7 1]
 [1 3]
 [6 0]]


Question 17: Array Splitting Operations


In [273]:
#Q17.1: Split an array into 3 equal parts using np.split()
array1 = np.random.randint(0,10,6)
split_array = np.split(array1, 3)
print(split_array)
for i, part in enumerate(split_array):
    print(f"Part {i+1}: {part}")


[array([3, 5], dtype=int32), array([1, 8], dtype=int32), array([0, 9], dtype=int32)]
Part 1: [3 5]
Part 2: [1 8]
Part 3: [0 9]


In [280]:
#Q17.2: Split an array at specific indices using np.split()
array1 = np.array([1,2,3,4,5,6,7,8,9])
split_indices =np.split(array1,[3,5,6])
print(split_indices)
for i, part in enumerate(split_indices):
    print(f"Part {i+1}: {part}")

[array([1, 2, 3]), array([4, 5]), array([6]), array([7, 8, 9])]
Part 1: [1 2 3]
Part 2: [4 5]
Part 3: [6]
Part 4: [7 8 9]


In [292]:
#Q17.3: Split an array horizontally using np.hsplit()
array1 = np.array([1,2,3,4,5,6,7,8])
h_split = np.hsplit(array1,4)
for i, part in enumerate(h_split):
    print("Part ",i+1,":",part)

Part  1 : [1 2]
Part  2 : [3 4]
Part  3 : [5 6]
Part  4 : [7 8]


In [287]:
#Q17.4: Split an array vertically using np.vsplit()

array1 = np.array([[1,2,3,4],[5,6,7,8]])
v_split = np.vsplit(array1,2)
for i, part in enumerate(v_split):
    print("Part ",i+1,":",part)

Part  1 : [[1 2 3 4]]
Part  2 : [[5 6 7 8]]


In [290]:
#Q17.5: Split an array into equal chunks using np.array_split()
array1 = np.array([1,2,3,4,5])
equal_chunks = np.array_split(array1,3)
for i, part in enumerate(equal_chunks):
    print("Part ",i+1,":",part)

Part  1 : [1 2]
Part  2 : [3 4]
Part  3 : [5]


Question 18: Array Repetition and Tiling


In [294]:
#Q18.1: Repeat each element of an array 3 times using np.repeat()
array1=np.array([1,2,3,4,5,6])
array2=np.repeat(array1,3)
print(array2)

[1 1 1 2 2 2 3 3 3 4 4 4 5 5 5 6 6 6]


In [295]:
#Q18.2: Repeat an entire array 2 times using np.tile()
array1=np.array([1,2,3,4,5,6])
array2=np.tile(array1,2)
print(array2)


[1 2 3 4 5 6 1 2 3 4 5 6]


In [302]:
#Q18.3: Repeat a 2D array using np.tile()
array1=np.array([[1,2,3],[4,5,6]])
array2=np.tile(array1,(2,2))
print(array2)
array2=np.tile(array1,2)
print(array2)

[[1 2 3 1 2 3]
 [4 5 6 4 5 6]
 [1 2 3 1 2 3]
 [4 5 6 4 5 6]]
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


In [303]:
#Q18.4: Create a pattern using np.tile()

pattern = np.array(['@', '#'])
result = np.tile(pattern, 5) 
print(result)

['@' '#' '@' '#' '@' '#' '@' '#' '@' '#']


In [ ]:
#Q18.5: Repeat elements with different counts using np.repeat()
arr = np.array([1, 2, 3])
repeats = [1, 3, 2] 
result = np.repeat(arr, repeats)
print(result)

[1 2 2 2 3 3]


Question 19: Array Comparison and Logical Operations


In [310]:
#Q19.1: Compare two arrays for equality using np.array_equal()
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([1,2,3,4])
print(np.array_equal(arr1,arr2))

False


In [312]:
#Q19.2: Check if arrays are close using np.allclose()
a = np.array([1.0, 2.0, 3.0])    #useful for float values  [ Absolute tolerance (atol),Relative tolerance (rtol)]
b = np.array([1.0, 2.000001, 2.999999])
result = np.allclose(a, b)
print(result)

True


In [325]:
##Q19.3: Apply logical AND operation between arrays
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,9])
and_op= np.logical_and(arr1>2,arr2>3)
print(and_op)

[False False  True]


In [ ]:
#Q19.4: Apply logical OR operation between arrays
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,9])
or_op= np.logical_or(arr1>2,arr2>8)
print(or_op)

[False False  True]


In [332]:
#Q19.5: Apply logical NOT operation to an array
arr1 = np.array([1,2,3])
not_op = np.logical_not(arr1)
print(not_op)
not_op = np.logical_not(arr1 == 2)
print(not_op)

[False False False]
[ True False  True]


Question 20: Array Set Operations


In [334]:
#Q20.1: Find unique elements in an array using np.unique()
arr1 = np.array([1,3,9,4,6,2,4,5,6,9,8,2,1,0,5])
unique = np.unique(arr1)
print(unique)

[0 1 2 3 4 5 6 8 9]


In [ ]:
#Q20.2: Find the intersection of two arrays using np.intersect1d()
a = np.random.randint(1,10,6)
b = np.random.randint(1,10,7)
print(a,b)
print(np.intersect1d(a,b))

[7 9 1 6 4 3] [5 4 4 8 2 9 1]
[1 4 9]


In [339]:
#Q20.3: Find the union of two arrays using np.union1d()
a = np.random.randint(1,10,6)
b = np.random.randint(1,10 ,7)
print(a,b)
print(np.union1d(a,b))

[5 8 9 5 1 8] [7 4 5 2 2 8 3]
[1 2 3 4 5 7 8 9]


In [ ]:
#Q20.4: Find elements in first array but not in second using np.setdiff1d()
a = np.random.randint(1,10,6)
b = np.random.randint(1,10,7)
print(a,b)
print(np.setdiff1d(a,b))

[2 1 7 1 5 7] [5 6 4 5 7 3 6]
[1 2]


In [342]:
#Q20.5: Find the symmetric difference between two arrays using np.setxor1d()
a = np.random.randint(1,10,8)
b = np.random.randint(1,10,7)
print(a,b)
print(np.setxor1d(a,b))

[3 5 4 3 5 9 1 7] [9 9 6 7 6 7 1]
[3 4 5 6]
