In [2]:
pip install numpy


   ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
   ----------- ---------------------------- 3.7/12.8 MB 20.4 MB/s eta 0:00:01
   ------------------ --------------------- 6.0/12.8 MB 13.3 MB/s eta 0:00:01
   --------------------------- ------------ 8.9/12.8 MB 13.7 MB/s eta 0:00:01
   ------------------------------------ --- 11.8/12.8 MB 13.5 MB/s eta 0:00:01
   ---------------------------------------- 12.8/12.8 MB 12.7 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
import numpy as np

# Manually created array: [Store ID, Sales, Customers, Inventory, Returns]
retail_data = np.array([
    [1, 25000, 300, 1200, 10],
    [2, 32000, 450, 1500, 15],
    [3, 28000, 380, 1100, 8],
    [4, 41000, 500, 1600, 20],
    [5, 35000, 420, 1400, 12],
    [6, 27000, 360, 1300, 9],
    [7, 39000, 480, 1700, 18],
    [8, 30000, 400, 1250, 14],
    [9, 45000, 550, 1800, 25],
    [10, 33000, 410, 1450, 11]
])

print(retail_data)


[[    1 25000   300  1200    10]
 [    2 32000   450  1500    15]
 [    3 28000   380  1100     8]
 [    4 41000   500  1600    20]
 [    5 35000   420  1400    12]
 [    6 27000   360  1300     9]
 [    7 39000   480  1700    18]
 [    8 30000   400  1250    14]
 [    9 45000   550  1800    25]
 [   10 33000   410  1450    11]]


In [5]:
## Basic Performance Analysis
#1. What is the **total revenue** generated across all stores?
revenue_total = np.sum(retail_data[:,1])
print(f"Total Revenue : {revenue_total}")

Total Revenue : 335000


In [14]:
#2. Which store recorded the **highest sales**?
highest_sale = np.argmax(retail_data[:,1])+1
print(f"Store which recorded highest sale: {highest_sale}")

Store which recorded highest sale: 9


In [9]:
#3. Which store recorded the **lowest sales**?
lowest_sale = np.argmin(retail_data[:,1])+1
print(f"Store which recorded lowest sale: {lowest_sale}")

Store which recorded lowest sale: 1


In [11]:
#4. What is the **average daily sales** per store?
average_sale = np.mean(retail_data[:,1])
print(f"Daily average sales: {average_sale}")

Daily average sales: 33500.0


In [ ]:
#5. How many stores achieved sales **above ₹35,000**?
stores_above_35000 = np.sum(retail_data[:, 1] > 35000) #return boolean values(caz of comparisons) which are added
print(stores_above_35000)

3


In [15]:
## Customer Insights
#6. Which store had the **highest customer footfall**?
highest_customer_footfall = np. argmax(retail_data[:,2])+1
print(highest_customer_footfall)

9


In [18]:
#7. What is the **average number of customers** per store?
avg_customers = np.mean(retail_data[:,2])
print(avg_customers)

425.0


In [19]:
#8. How many stores have **more than 450 customers**?
customers_above_450 = np.sum(retail_data[:,2] > 450)
print(customers_above_450)

3


In [21]:
#9. Which store has the **lowest customer count**?
lowest_customer_count = np.argmin(retail_data[:,2])+1
print(lowest_customer_count)

1


In [24]:
#10. Is there any store where **high sales do not correspond to high customers**?
high_sales_low_customers = retail_data[(retail_data[:, 1] > average_sale) & (retail_data[:, 2] < avg_customers)]
print(high_sales_low_customers)

[[    5 35000   420  1400    12]]


In [ ]:
## Inventory & Returns Analysis
#11. What is the **total inventory** across all stores?
total_inventory = np.sum(retail_data[:,3])
print(total_inventory)

14300


In [ ]:
#12. Which store has the **highest inventory stock**?
highest_inventory_stock_store = np.argmax(retail_data[:,3])+1
print(highest_inventory_stock_store)


9


In [27]:
#13. How many stores have **inventory less than 1300 units**?
inventory_less_than_1300 = np.sum(retail_data[:,3] < 1300)
print(inventory_less_than_1300)

3


In [30]:
#14. Which store has the **highest return rate** (returns ÷ inventory)?
returns = retail_data[:,4]
inventory = retail_data[:,3]
return_rate = returns / inventory
highest_return_rate = np.argmax(return_rate)+1
print(f"Store with highest return rate: {highest_return_rate}")

Store with highest return rate: 9


In [ ]:
#15. Which stores have **returns greater than 15 units**?
return_greater_than_15 = np.sum(retail_data[:,4] > 15)
print(return_greater_than_15)

return_greater_than_15 =retail_data[retail_data[:, 4] > 15, 0]
print(return_greater_than_15)

3
[4 7 9]


In [43]:
## Sales & Customer Correlation
#16. Is there a **positive correlation** between sales and customers?
sales = retail_data[:,1]
customers = retail_data[:,2]
correlation = np.corrcoef(sales, customers)[1,0]
positive_corr = correlation > 0
print(correlation)
print(f"Is there positive correlation: {positive_corr}")

0.9593636912502479
Is there positive correlation: True


In [ ]:
#17. Which store has **high customer visits but low sales**?
high_customer_low_sales = retail_data[(retail_data[:,1] < average_sale) & (retail_data[:,2] > avg_customers)]
print(high_customer_low_sales)

[[    2 32000   450  1500    15]]


In [47]:
#18. Which store has **low customers but high sales**?
low_customer_high_sales = retail_data[(retail_data[:,1] > average_sale) & (retail_data[:,2] < avg_customers)]
print(low_customer_high_sales)

[[    5 35000   420  1400    12]]


In [56]:
#19. How many stores have **sales per customer above ₹90**?
sales_per_customer = retail_data[:,1] / retail_data[:,2]
store_above_90 = retail_data[sales_per_customer > 90]
print(store_above_90)

[]


In [53]:
#20. Which stores could **benefit from customer acquisition campaigns** (low customers, high inventory)?
avg_customers = np.mean(retail_data[:,2])
avg_inventory = np.mean(retail_data[:,3])
low_customer_high_inventory = retail_data[(retail_data[:,2] < avg_customers) & (retail_data[:,3] > avg_inventory)]
print(low_customer_high_inventory)

[[   10 33000   410  1450    11]]


In [57]:
## Profitability & Growth
#21. If profit margin is **20% of sales**, what is the **profit per store**?
profit_per_store = retail_data[:,1] * 0.20
print(profit_per_store)

[5000. 6400. 5600. 8200. 7000. 5400. 7800. 6000. 9000. 6600.]


In [76]:
#22. Which store has the **highest profit**?
highest = np.argmax(profit_per_store)
highest_profit = retail_data[highest]
print(f"Store is {highest+1} with highest profit :  {highest_profit}")

Store is 9 with highest profit :  [    9 45000   550  1800    25]


In [75]:
#23. Which store has the **lowest profit**?
lowest = np.argmin(profit_per_store)
lowest_profit = retail_data[lowest]
print(f"Store is {lowest+1} with lowest profit :  {lowest_profit}")

Store is 1 with lowest profit :  [    1 25000   300  1200    10]


In [70]:
#24. If sales increase by **10% next month**, what are the **new sales figures**?
new_sale_figures = retail_data[:,1] * 1.10  #to calculate new increased amount = 1+ increase precentage / 100 
print("New sale figures : ",new_sale_figures)  # if its 20% ,then its 1.20

New sale figures :  [27500. 35200. 30800. 45100. 38500. 29700. 42900. 33000. 49500. 36300.]


In [74]:
#Profit per store = sales * profit_margin  (retail_data[:,1] *0.20)
#Profit margin = 20% → 0.20 in decimal form
# New sales after 10% increase = new_sale_figures  (retail_data[:,1] *1.10)
# New profit after increase = new_sale_figures * 0.20   
#25. How will **total profit** change with the 10% sales increase?
old_total_profit = np.sum(profit_per_store)
new_total_profit = np.sum(new_sale_figures * 0.20)
profit_change = new_total_profit - old_total_profit
print(old_total_profit)
print(new_total_profit)
print(profit_change)


67000.0
73700.0
6700.0


In [ ]:
## Operational Strategy
#26. Which stores need **inventory restocking** based on sales and current stock?
# means sales > avg_sale and inventory < average_inventory
avg_inventory = np.mean(retail_data[:, 3])
avg_sales = np.mean(retail_data[:, 1])
restock_needed = retail_data[(retail_data[:, 3] < avg_inventory) & (retail_data[:, 1] > avg_sales)]
print("Stores that need restocking :\n",restock_needed)


Stores that need restocking :
 [[    5 35000   420  1400    12]]


In [85]:
#27. Which stores show **high returns percentage** and might require **quality checks**?
#return_percentages = returns /sales * 100
#calculate avg_return_percentage using np.mean(return_percentages)
#extract return_percentages > avg_return_percentage

sales = retail_data[:,1]
returns = retail_data[:,4]
return_percentages = returns / sales * 100
avg_return_percentage = np.mean(return_percentages)
high_return_percentage = retail_data[return_percentages > avg_return_percentage]
print("Stores which show high return percentages that might requrie quality checks :\n", high_return_percentage)


Stores which show high return percentages that might requrie quality checks :
 [[    2 32000   450  1500    15]
 [    4 41000   500  1600    20]
 [    7 39000   480  1700    18]
 [    8 30000   400  1250    14]
 [    9 45000   550  1800    25]]


In [86]:
#28. Which store is the **best performer overall** (sales, customers, inventory turnover)?
# Extract relevant columns
sales = retail_data[:, 1]
customers = retail_data[:, 2]
inventory = retail_data[:, 3]

# Calculate inventory turnover
inventory_turnover = sales / inventory  #High turnover means a store sells stock quickly 

# Normalize each metric (0–1 scale)  # Xnorm = x - min(x)  / max(x) - min(x)
sales_norm = (sales - sales.min()) / (sales.max() - sales.min())
customers_norm = (customers - customers.min()) / (customers.max() - customers.min())
turnover_norm = (inventory_turnover - inventory_turnover.min()) / (inventory_turnover.max() - inventory_turnover.min())

# Weighted score (equal weight for simplicity)
overall_score = sales_norm + customers_norm + turnover_norm

# Find best performer
best_index = np.argmax(overall_score)+1

print(f"Best performer overall is Store: {best_index}")


Best performer overall is Store: 9


In [87]:
#29. Which store is the **worst performer overall**?
worst_performer = np.argmin(overall_score)+1
print(f"Worst performer overall is Store: {worst_performer}")


Worst performer overall is Store: 1


In [89]:
#30. Which stores can be considered for **expansion** based on strong sales and customer metrics?
# Sales > average sales
# Customers > average customers
avg_sales = np.mean(retail_data[:, 1])
avg_customers = np.mean(retail_data[:, 2])

expansion_candidates = retail_data[(retail_data[:, 1] > avg_sales) & (retail_data[:, 2] > avg_customers)]
print("Expansion candidates:\n", expansion_candidates)


Expansion candidates:
 [[    4 41000   500  1600    20]
 [    7 39000   480  1700    18]
 [    9 45000   550  1800    25]]
